version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: control_inventario_db
    environment:
      POSTGRES_DB: control_inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/config/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - inventario_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: control_inventario_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: control_inventario
      DB_USER: postgres
      DB_PASSWORD: postgres123
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - inventario_network
    volumes:
      - ./backend:/app
    command: npm run server

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: control_inventario_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inventario_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  inventario_network:
    driver: bridge



